[package]
name = "katwalk"
version = "0.0.17"
edition = "2021"
authors = ["Krzysztof Kwiatkowski"]
description = "Client for testing cryptographic implementations against KAT vectors"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kriskwiatkowski/katwalk"
homepage = "https://github.com/kriskwiatkowski/katwalk"


[dependencies]
hqc = { package = "hqckem-ref", version = "0.0.2" }
mlkem-ref = { package = "mlkem-ref", version = "0.0.1" }
ml-dsa = { version = "0.1.1", default-features = false, features = ["rand_core"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = [
    "json",
    "rustls-tls",
], default-features = false }
base64 = "0.22"
hex = "0.4"
sha3 = "0.10"
sha2 = "0.10"
hmac = "0.12"
totp-lite = "2.0"
x509-parser = "0.16"
zip = "0.6"
log = "0.4"
env_logger = "0.11"

[[bin]]
name = "katwalk"
path = "src/main.rs"

[[bin]]
name = "mlkem_wrapper"
path = "src/bin/mlkem_wrapper.rs"

[[bin]]
name = "hqckem_wrapper"
path = "src/bin/hqckem_wrapper.rs"

[[bin]]
name = "mldsa_wrapper"
path = "src/bin/mldsa_wrapper.rs"

[[bin]]
name = "fips202_wrapper"
path = "src/bin/fips202_wrapper.rs"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"
