[book]
title = "katwalk Documentation"
authors = ["Krzysztof Kwiatkowski"]
language = "en"
src = "src"

[preprocessor.links]

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/kriskwiatkowski/katwalk"
edit-url-template = "https://github.com/kriskwiatkowski/katwalk/edit/main/docs/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false

[output.html.search]
enable = true
